### PR TITLE
Remove second locked-in-place toolbar button

### PR DESCRIPTION
**Pull request by DaAwesomeP**
Fix for #17, read https://github.com/livereload/livereload-extensions/issues/17#issuecomment-41976963. Also for #28.

### CODE REVIEW

**Comment by andreyvit** [comment]
All right! This is finally merged. Sorry that it took so very long to get to it. I'll review the rest of the changes, and will publish new extensions next week.

**Comment by flying-sheep** [comment]
hi, could you upload the new version, please?

**Comment by andreyvit** [comment]
The new version is released now. Unfortunately, I have permanently lost my Firefox update private key (which I previously used to sign updates), so the extension won't autoupdate; you need to redownload it from [livereload.com/extensions/](http://livereload.com/extensions/).

**Comment by flying-sheep** [comment]
well, time to create a new key then :grin:

**Pull request merged**
